TRUNCATE inprog.rooms RESTART IDENTITY CASCADE;

TRUNCATE inprog.types RESTART IDENTITY CASCADE;

TRUNCATE inprog.users RESTART IDENTITY CASCADE;

TRUNCATE inprog.bookings RESTART IDENTITY CASCADE;

TRUNCATE inprog.categories RESTART IDENTITY CASCADE;

TRUNCATE inprog.payments RESTART IDENTITY CASCADE;

TRUNCATE inprog.facilities RESTART IDENTITY CASCADE;

